<a href="https://colab.research.google.com/github/anjalibajpai768-cell/AI-ML-INTERNSHIP/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello

In [ ]:
name_full = ("Anjali Bajpai")
print(name_full)

Anjali Bajpai

In [ ]:
Name = ("Anjali Bajpai")
Address = ("Jankipuram Lucknow")
College_Name = ("SRMCEM")
print(Name)
print(Address)
print(College_Name)

Anjali Bajpai
Jankipuram Lucknow
SRMCEM

In [ ]:
a = 2
b = 10
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)

12
-8
20
0.2
2
1024
0

In [ ]:
a = 12
print(type(a))

<class 'int'>

In [ ]:
a = 12 ,  'Name'
print(type(a))

<class 'tuple'>

In [ ]:
name = input("Enter your name")
print(name)

address = input("Enter your address")
print(address)

age = input("Enter your age")
print(age)

department = input("Enter your department")
print(department)

phonenumber = input("Enter your phone number")
print(phonenumber)

Enter your nameAnjali Bajpai
Anjali Bajpai
Enter your addressJankipuram Lucknow
Jankipuram Lucknow
Enter your age19
19
Enter your departmentAI ML
AI ML

In [7]:
a = ("10")
print(int(a)+5)

15

In [8]:
a = ("10.55")
print(float(a))

10.55

In [9]:
a = ("10.55")
print(int(float(a)))

10

In [11]:
name = ("anjali bajpai")
print(name.upper())
print(name.lower())
print(name.title())
print(name.capitalize())
print(len(name))
print(name.replace("anjali bajpai","anjali"))

ANJALI BAJPAI
anjali bajpai
Anjali Bajpai
Anjali bajpai
13
anjali

In [12]:
age = 40
if age>=18:
  print("You are eligible for voting")
else:
  print("You are not eligible for voting")

You are eligible for voting

In [13]:
marks = 90
rank = 48000
if marks>=90:
  print("Grade A")
elif marks>=80:
  print("Grade B")
elif marks>=70:
  print("Grade C")

Grade A

In [16]:
age = 55
if age>60:
  print("Senior citizen")
elif age==60 and age>35:
  print("Middle age")
elif age<35:
  print("Young")
else:
  print("Kids")

Kids

In [19]:
marks = int(input("Enter the marks"))
if marks>=90:
  print("Grade A")
elif marks>=80:
  print("Grade B")
elif marks>=70:
  print("Grade C")
elif marks>=60:
  print("Grade D")
else:
  print("Grade E")

Enter the marks45
Grade E

In [20]:
number = int(input("Enter the number"))
if number%2==0:
  print("Even number")
else:
  print("Odd number")

Enter the number14
Even number

In [21]:
number = int(input("Enter the number"))
if number%2!=0:
  print("Odd number")
else:
  print("Even number")

Enter the number21
Odd number

In [23]:
n = int(input("Enter the number"))
if n%3==0 & n%5==0:
  print("Divisible by 3 and 5")
else:
  print("Not divisible by 3 and 5")

Enter the number15
Divisible by 3 and 5

In [24]:
balance = int(input("enter the amount"))
withdraw = int(input("enter the money to be withdrawn"))
if withdraw <= balance:
  print("withdrawl successful")
else:
  print("insufficient balance")

enter the amount4800
enter the money to be withdrawn55
withdrawl successful

In [25]:
password = input("Enter the password")
if password == "hello":
  print("Password is correct")
else:
  print("Password is incorrect")

Enter the passwordanjali
Password is incorrect

In [26]:
n = input("Enter the number")
if n == n[::-1]:
  print("Palindrome")
else:
  print("Not Palindrome")

Enter the number143
Not Palindrome

In [28]:
n = input("Enter the number")
if len(n) == 2:
  print("Two digit number")
else:
  print("Not a two digit number")

Enter the number4
Not a two digit number

In [30]:
for i in range(25):
 print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24

In [31]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9

In [32]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9

In [33]:
for i in range(7,71,7):
 print(i)

7
14
21
28
35
42
49
56
63
70

In [34]:
for i in range(10,0,-1):
  print(i)

10
9
8
7
6
5
4
3
2
1

In [35]:
for i in range(50,4,-5):
  print(i)

50
45
40
35
30
25
20
15
10
5

In [37]:
for i in range(1,10):
  if i==6:
     continue
  print(i)

1
2
3
4
5
7
8
9

In [38]:
a = 12
b = 11
a,b = b,a
print(a)
print(b)

11
12

In [39]:
a = int(input("Enter First number"))
b = int(input("Enter Second number"))
print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)
print("Modulus",a%b)
print("Exponent",a**b)
print("Floor Division",a//b)

Enter First number14
Enter Second number25
Addition 39
Subtraction -11
Multiplication 350
Division 0.56
Modulus 14
Exponent 44998795805848373114515226624
Floor Division 0

In [40]:
a = int(input("Enter first number"))
b = int(input("Enter second number"))
Add = a+b
print("Addition is:",Add)
Sub = a-b
print("Subtraction is:",Sub)
Mul = a*b
print("Multiplication is:",Mul)
Div = a/b
print("Division is:",Div)

Enter first number5
Enter second number9
Addition is: 14
Subtraction is: -4
Multiplication is: 45
Division is: 0.5555555555555556

In [42]:
import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
name = "Anjali"
print(name[1])
print(name[-3])
print(name[0:2]) #slicing
print(name[0:9])

n
a
An
Anjali

In [ ]:
name ="I love to read books"
print(name[0:2])
print(name[0:9])
print(name[4:6])
print(name[::-1])
rev = print(name[::-1])

I
I love to
ve
skoob daer ot evol I
skoob daer ot evol I

In [ ]:
name ="Anjali"
title = "HEllo"
print(name + title)
print(name + " " + title)
print(name.upper())
print(name.lower())
print(name.title())
print(name.capitalize())
print(len(name))
print(name.count("a"))
print(name.replace("HEllo","Anjali"))
print(name.replace("Anjali","HEllo"))
print(name.find("n"))
print(title.find("l"))
print(name.split())
print(title.split())
print(len(title))
name_title = name + title
print(name_title)

AnjaliHEllo
Anjali HEllo
ANJALI
anjali
Anjali
Anjali
6
1
Anjali
HEllo
1
2
['Anjali']
['HEllo']
5
AnjaliHEllo

In [ ]:
a=[10,20,30]
b=[40,20]
print(a+b)
print(a[0])   #indexing
print(a[0:2])
print([10,20]*5)
print(20 in [10,20,30])
a.extend([10,20])
print(a)
a.remove(10)
print(a)
a.sort()
print(a)
a.reverse()
print(a)
print(a.index(10)) #reverse condition is placed before
print(a.count(20))

[10, 20, 30, 40, 20]
10
[10, 20]
[10, 20, 10, 20, 10, 20, 10, 20, 10, 20]
True
[10, 20, 30, 10, 20]
[20, 30, 10, 20]
[10, 20, 20, 30]
[30, 20, 20, 10]
3
2

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Zomato-data-.csv')

In [ ]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [ ]:
#one dimensional data
import pandas as pd
marks = pd.Series([85,90,78,95])
print (marks)

0    85
1    90
2    78
3    95
dtype: int64

In [ ]:
df = pd.read_csv('/content/Zomato-data-.csv.xlsx')

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df.shape

(148, 7)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [ ]:
df.sample()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,800,Buffet

In [ ]:
df.dtypes

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [ ]:
df['approx_cost(for two people)'].describe()

count    148.000000
mean     418.243243
std      223.085098
min      100.000000
25%      200.000000
50%      400.000000
75%      600.000000
max      950.000000
Name: approx_cost(for two people), dtype: float64

In [ ]:
df["name"]  #selecting single column data
df[["name","online_order"]]  #selecting multiple column data

                      name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [ ]:
df.sort_values("Salary") #ascending order
# df["votes"] # This column does not exist in the current DataFrame
"""
df.sort_values("votes",ascending=False) #descending order

df.sort_values(["Department","Salary"]) #mulriple column sorting

df["Bonus"]= df["Salary"]*0.18  #adding new column

df["Total Salary"]=df["Salary"]+df["Bonus"]  #adding new column
"""

'\ndf.sort_values("votes",ascending=False) #descending order\n\ndf.sort_values(["Department","Salary"]) #mulriple column sorting\n\ndf["Bonus"]= df["Salary"]*0.18  #adding new column\n\ndf["Total Salary"]=df["Salary"]+df["Bonus"]  #adding new column\n'

In [ ]:
import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df.head()

   Emp_ID   Name  Age Department  Salary     City
0     101   Aman   24         HR   35000    Delhi
1     102   Neha   25         IT   50000  Lucknow
2     103  Rahul   23      Sales   45000    Noida
3     104  Priya   28         IT   60000    Delhi
4     105  Karan   30         HR   38000   Jaipur

In [ ]:
df.tail()

   Emp_ID    Name  Age Department  Salary     City
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df.sample()

   Emp_ID    Name  Age Department  Salary   City
7     108  Anjali   24         IT   62000  Delhi

In [ ]:
df.shape

(10, 6)

In [ ]:
df.columns

Index(['Emp_ID', 'Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
 5   City        10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [ ]:
df.describe()

          Emp_ID        Age        Salary
count   10.00000  10.000000     10.000000
mean   105.50000  26.100000  49000.000000
std      3.02765   2.330951   9580.071909
min    101.00000  23.000000  35000.000000
25%    103.25000  24.250000  41250.000000
50%    105.50000  25.500000  48500.000000
75%    107.75000  27.750000  57250.000000
max    110.00000  30.000000  62000.000000

In [ ]:
df.dtypes

Emp_ID         int64
Name          object
Age            int64
Department    object
Salary         int64
City          object
dtype: object

In [ ]:
df["Name"]

0      Aman
1      Neha
2     Rahul
3     Priya
4     Karan
5    Simran
6     Mohit
7    Anjali
8     Vikas
9     Pooja
Name: Name, dtype: object

In [ ]:
df[["Name","Salary"]]

     Name  Salary
0    Aman   35000
1    Neha   50000
2   Rahul   45000
3   Priya   60000
4   Karan   38000
5  Simran   55000
6   Mohit   47000
7  Anjali   62000
8   Vikas   58000
9   Pooja   40000

In [ ]:
df[df["Salary"]>5000]

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df[df["Department"]=='IT']

   Emp_ID    Name  Age Department  Salary     City
1     102    Neha   25         IT   50000  Lucknow
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df[df["Age"]==25]

   Emp_ID   Name  Age Department  Salary     City
1     102   Neha   25         IT   50000  Lucknow
9     110  Pooja   25         HR   40000    Delhi

In [ ]:
df[(df["Salary"]>5000) & (df["Department"]=="IT")]

   Emp_ID    Name  Age Department  Salary     City
1     102    Neha   25         IT   50000  Lucknow
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df.sort_values("Salary")

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
4     105   Karan   30         HR   38000   Jaipur
9     110   Pooja   25         HR   40000    Delhi
2     103   Rahul   23      Sales   45000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
1     102    Neha   25         IT   50000  Lucknow
5     106  Simran   26    Finance   55000    Noida
8     109   Vikas   29    Finance   58000   Jaipur
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df.sort_values("Salary" , ascending=False)

   Emp_ID    Name  Age Department  Salary     City
7     108  Anjali   24         IT   62000    Delhi
3     104   Priya   28         IT   60000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
5     106  Simran   26    Finance   55000    Noida
1     102    Neha   25         IT   50000  Lucknow
6     107   Mohit   27      Sales   47000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
9     110   Pooja   25         HR   40000    Delhi
4     105   Karan   30         HR   38000   Jaipur
0     101    Aman   24         HR   35000    Delhi

In [ ]:
df["Salary"].max()

62000

In [ ]:
df["Salary"].min()

35000

In [ ]:
df["Salary"].mean()

np.float64(49000.0)

In [ ]:
df["Salary"].sum()

np.int64(490000)

In [ ]:
df["Name"].count()

np.int64(10)

In [ ]:
df["Department"].unique()

array(['HR', 'IT', 'Sales', 'Finance'], dtype=object)

In [ ]:
df["Department"].nunique()

4

In [ ]:
df["Bonus"]=df["Salary"]*0.5
df

   Emp_ID Emp_name  Age Department  Salary     City    Bonus
0     101     Aman   24         HR   35000    Delhi  17500.0
1     102     Neha   25         IT   50000  Lucknow  25000.0
2     103    Rahul   23      Sales   45000    Noida  22500.0
3     104    Priya   28         IT   60000    Delhi  30000.0
4     105    Karan   30         HR   38000   Jaipur  19000.0
5     106   Simran   26    Finance   55000    Noida  27500.0
6     107    Mohit   27      Sales   47000  Lucknow  23500.0
7     108   Anjali   24         IT   62000    Delhi  31000.0
8     109    Vikas   29    Finance   58000   Jaipur  29000.0
9     110    Pooja   25         HR   40000    Delhi  20000.0

In [ ]:
df.rename(columns={"Name":"Emp_name"})

   Emp_ID Emp_name  Age Department  Salary     City    Bonus
0     101     Aman   24         HR   35000    Delhi  17500.0
1     102     Neha   25         IT   50000  Lucknow  25000.0
2     103    Rahul   23      Sales   45000    Noida  22500.0
3     104    Priya   28         IT   60000    Delhi  30000.0
4     105    Karan   30         HR   38000   Jaipur  19000.0
5     106   Simran   26    Finance   55000    Noida  27500.0
6     107    Mohit   27      Sales   47000  Lucknow  23500.0
7     108   Anjali   24         IT   62000    Delhi  31000.0
8     109    Vikas   29    Finance   58000   Jaipur  29000.0
9     110    Pooja   25         HR   40000    Delhi  20000.0

In [ ]:
df.drop("Bonus",axis=1,inplace=True,errors = 'ignore')
df

   Emp_ID Emp_name  Age Department
0     101     Aman   24         HR
1     102     Neha   25         IT
2     103    Rahul   23      Sales
3     104    Priya   28         IT
4     105    Karan   30         HR
5     106   Simran   26    Finance
6     107    Mohit   27      Sales
7     108   Anjali   24         IT
8     109    Vikas   29    Finance
9     110    Pooja   25         HR

In [ ]:
df.isnull()

   Emp_ID  Emp_name    Age  Department
0   False     False  False       False
1   False     False  False       False
2   False     False  False       False
3   False     False  False       False
4   False     False  False       False
5   False     False  False       False
6   False     False  False       False
7   False     False  False       False
8   False     False  False       False
9   False     False  False       False

In [ ]:
df.drop("City",axis=1,inplace = True,errors = 'ignore')
df

   Emp_ID Emp_name  Age Department
0     101     Aman   24         HR
1     102     Neha   25         IT
2     103    Rahul   23      Sales
3     104    Priya   28         IT
4     105    Karan   30         HR
5     106   Simran   26    Finance
6     107    Mohit   27      Sales
7     108   Anjali   24         IT
8     109    Vikas   29    Finance
9     110    Pooja   25         HR

In [ ]:
df.isnull().sum()

Emp_ID        0
Emp_name      0
Age           0
Department    0
dtype: int64

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Emp_name"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Emp_name, dtype: bool

In [ ]:
df[df['City']] = 'Delhi'
df

   Emp_ID Emp_name  Age Department   City  Delhi
0     101     Aman   24         HR  Delhi  Delhi
1     102     Neha   25         IT  Delhi  Delhi
2     103    Rahul   23      Sales  Delhi  Delhi
3     104    Priya   28         IT  Delhi  Delhi
4     105    Karan   30         HR  Delhi  Delhi
5     106   Simran   26    Finance  Delhi  Delhi
6     107    Mohit   27      Sales  Delhi  Delhi
7     108   Anjali   24         IT  Delhi  Delhi
8     109    Vikas   29    Finance  Delhi  Delhi
9     110    Pooja   25         HR  Delhi  Delhi

In [ ]:
import pandas as pd

data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja",
             "Rohit","Sneha","Arjun","Riya","Deepak",
             "Muskan","Yash","Komal","Abhishek","Nisha"],

    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female",
               "Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],

    "Age": [20,21,19,22,20,21,20,19,22,20,
            21,20,23,19,22,20,21,22,20,19],

    "Department": ["CSE","IT","ECE","CSE","IT",
                   "CSE","ECE","IT","CSE","ECE",
                   "IT","CSE","ECE","IT","CSE",
                   "ECE","IT","CSE","ECE","IT"],

    "Semester": [4,4,2,6,4,6,2,4,8,6,
                 2,8,6,4,8,2,6,4,8,2],

    "Marks": [85,92,78,95,67,88,72,91,81,76,
              69,94,73,89,97,66,82,90,79,84],

    "Attendance": [92,95,85,97,78,90,82,98,88,84,
                   80,96,83,91,99,76,89,94,87,92],

    "CGPA": [8.5,9.2,7.8,9.5,6.9,
             8.8,7.2,9.1,8.1,7.6,
             7.0,9.4,7.4,8.9,9.8,
             6.8,8.2,9.0,7.9,8.4],

    "City": ["Delhi","Lucknow","Noida","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

    Student_ID      Name  Gender  Age Department  Semester  Marks  Attendance  \
0          101      Aman    Male   20        CSE         4     85          92
1          102      Neha  Female   21         IT         4     92          95
2          103     Rahul    Male   19        ECE         2     78          85
3          104     Priya  Female   22        CSE         6     95          97
4          105     Karan    Male   20         IT         4     67          78
5          106    Simran  Female   21        CSE         6     88          90
6          107     Mohit    Male   20        ECE         2     72          82
7          108    Anjali  Female   19         IT         4     91          98
8          109     Vikas    Male   22        CSE         8     81          88
9          110     Pooja  Female   20        ECE         6     76          84
10         111     Rohit    Male   21         IT         2     69          80
11         112     Sneha  Female   20        CSE         8     94          96
12         113     Arjun    Male   23        ECE         6     73          83
13         114      Riya  Female   19         IT         4     89          91
14         115    Deepak    Male   22        CSE         8     97          99
15         116    Muskan  Female   20        ECE         2     66          76
16         117      Yash    Male   21         IT         6     82          89
17         118     Komal  Female   22        CSE         4     90          94
18         119  Abhishek    Male   20        ECE         8     79          87
19         120     Nisha  Female   19         IT         2     84          92

    CGPA     City
0    8.5    Delhi
1    9.2  Lucknow
2    7.8    Noida
3    9.5   Jaipur
4    6.9    Delhi
5    8.8    Noida
6    7.2  Lucknow
7    9.1    Delhi
8    8.1   Jaipur
9    7.6    Delhi
10   7.0    Noida
11   9.4  Lucknow
12   7.4    Delhi
13   8.9   Jaipur
14   9.8    Delhi
15   6.8    Noida
16   8.2  Lucknow
17   9.0    Delhi
18   7.9   Jaipur
19   8.4    Delhi